version: "3"

services:
  mysql:
    image: mysql:latest
    ports: 
     - "3306:3306"
    user: "$UID:$GID"
    volumes:
     - ./volumes/mysql:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
  grafana:
    image: grafana/grafana:6.5.0
    ports:
      - 3000:3000
    user: "$UID:$GID"
    volumes:
      - ./volumes/grafana:/var/lib/grafana

